#!/usr/bin/env python

import os
import gzip

class Ubyte:
    def __init__(self, image=None, label=None, t=None, num_item=None, num_row=None, num_col=None):
        self.data = data
        self.label = label
        self.type = t
        self.num_item = num_item
        self.num_col = num_col
        self.num_row = num_row

    def saveFile(self, file_name=None, folder_path=None, is_zipped=True):
        """
            This function is responsible for creating or saving the UByte file.
            If the file name is kept None, the function will create a random name for the file.
            If the folder path is kept none, the function will save the file in the current folder.
            
            Args:
                - file_name, a string or None. The file name for the file to be saved.
                - folder_path: a string or None. The folder path for the file to be saved.
                - is_zipped: a bool. If is True, the function will zip the file
        """
        return None
 
if __name__ == "__main__":
    
